/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_temperature_measurement        21
#define gattdb_temperature_type               24
#define gattdb_intermediate_temperature       27
#define gattdb_measurement_interval           30
#define gattdb_valid_range                    31
#define gattdb_employee_id_s                  35
#define gattdb_employee_id_server             37
#define gattdb_attendance_data_c              40
#define gattdb_employee_data_client           42
#define gattdb_wages                          44
#define gattdb_wages_client                   46
#define gattdb_button_state                   49
#define gattdb_ota_control                    53


#endif // __GATT_DB_H
